import React, { useState } from 'react';
import {
  Sparkles,
  TrendingUp,
  TrendingDown,
  Calendar,
  FileText,
  Printer,
  Share2,
  Award,
  CheckCircle2,
  AlertCircle,
  Clock,
  Heart,
  Activity,
  ShieldCheck,
  ChevronRight,
  Flame,
  Droplets,
  Moon,
  Loader2,
  Copy,
  Check
} from 'lucide-react';
import { useHealth } from '../../context/HealthContext';
import { HISTORICAL_TIMELINE, PREVENTIVE_SCREENINGS } from '../../data/demoData';
import { geminiService } from '../../services/geminiService';
import { DoctorPrepSummary } from '../../types/health';
import { SafetyBanner } from '../common/SafetyBanner';

export const InsightsView: React.FC = () => {
  const {
    patient,
    labResults,
    todayActivity,
    appointments,
    medications,
    symptoms,
    healthGoals,
    toggleGoalComplete,
    badges,
    triggerCelebration,
    openAssistantWithPrompt
  } = useHealth();

  const [activeTab, setActiveTab] = useState<'insights' | 'report' | 'doctor-prep' | 'timeline' | 'preventive' | 'goals'>('insights');
  const [selectedPeriod, setSelectedPeriod] = useState('September 2026');
  const [isGeneratingReport, setIsGeneratingReport] = useState(false);
  const [generatedReport, setGeneratedReport] = useState<any>(null);

  // Doctor visit prep state
  const [isGeneratingPrep, setIsGeneratingPrep] = useState(false);
  const [prepSummary, setPrepSummary] = useState<DoctorPrepSummary | null>(null);
  const [copiedPrep, setCopiedPrep] = useState(false);

  const upcomingApt = appointments.find(a => a.status === 'upcoming') || appointments[0];

  const handleGenerateReport = async () => {
    setIsGeneratingReport(true);
    try {
      const rep = await geminiService.generateHealthReport(selectedPeriod, {
        patient,
        labResults,
        todayActivity
      });
      setGeneratedReport(rep);
      triggerCelebration();
    } finally {
      setIsGeneratingReport(false);
    }
  };

  const handleGenerateDoctorPrep = async () => {
    setIsGeneratingPrep(true);
    try {
      const recentLdl = labResults.find(l => l.testName.includes('LDL'))?.value?.toString();
      const recentChol = labResults.find(l => l.testName.includes('Total'))?.value?.toString();
      const recentHba1c = labResults.find(l => l.testName.includes('HbA1c'))?.value?.toString();

      const result = await geminiService.generateDoctorPrep(upcomingApt, {
        age: patient.age,
        gender: patient.gender,
        cholesterol: recentChol,
        ldl: recentLdl,
        hba1c: recentHba1c,
        bp: `${todayActivity.systolicBP}/${todayActivity.diastolicBP} mmHg`,
        medications: medications.map(m => `${m.name} ${m.dosage}`),
        symptoms: symptoms.map(s => `${s.symptom} (severity ${s.severity}/10)`)
      });

      setPrepSummary(result);
      triggerCelebration();
    } finally {
      setIsGeneratingPrep(false);
    }
  };

  const copyPrepToClipboard = () => {
    if (!prepSummary) return;
    const text = `PATIENT HEALTH CONSULTATION BRIEF
Patient: ${patient.name} (${patient.age}y ${patient.gender})
Doctor: ${upcomingApt.doctor} (${upcomingApt.specialty})
Purpose: ${upcomingApt.purpose}

EXECUTIVE SUMMARY:
${prepSummary.executiveSummary}

KEY METRICS:
${prepSummary.keyMetricsToHighlight.map(m => `- ${m.metric}: ${m.value} (${m.status}) - ${m.note}`).join('\n')}

RECENT LIFESTYLE CHANGES:
${prepSummary.recentChanges.join('\n')}

QUESTIONS FOR DOCTOR:
${prepSummary.recommendedQuestionsForDoctor.map((q, i) => `${i + 1}. ${q}`).join('\n')}

*Generated by AuraHealth AI*`;

    navigator.clipboard.writeText(text);
    setCopiedPrep(true);
    setTimeout(() => setCopiedPrep(false), 2000);
  };

  return (
    <div className="space-y-6 pb-16 animate-in fade-in duration-200">
      {/* Sub Tabs Navigation */}
      <div className="bg-white dark:bg-slate-900 p-2 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-xs flex items-center gap-1.5 overflow-x-auto no-scrollbar">
        {[
          { id: 'insights', label: 'AI Health Insights', icon: Sparkles },
          { id: 'doctor-prep', label: 'Doctor Visit Summary', icon: FileText },
          { id: 'report', label: 'Monthly Health Report', icon: Printer },
          { id: 'preventive', label: 'Preventive Screenings', icon: ShieldCheck },
          { id: 'timeline', label: 'Unified Timeline', icon: Clock },
          { id: 'goals', label: 'Goals & Badges', icon: Award }
        ].map((tab) => {
          const Icon = tab.icon;
          const isActive = activeTab === tab.id;
          return (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id as any)}
              className={`flex items-center gap-2 px-3.5 py-2 rounded-xl text-xs font-bold whitespace-nowrap transition-all ${
                isActive
                  ? 'bg-cyan-600 text-white shadow-xs'
                  : 'text-slate-600 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-800'
              }`}
            >
              <Icon className="w-3.5 h-3.5" />
              <span>{tab.label}</span>
            </button>
          );
        })}
      </div>

      {/* TAB 1: AI HEALTH INSIGHTS */}
      {activeTab === 'insights' && (
        <div className="space-y-6">
          <div>
            <h2 className="text-xl font-bold text-slate-900 dark:text-white">
              Evidence-Based Health Trends & Correlations
            </h2>
            <p className="text-xs text-slate-500">
              Deep machine learning synthesis evaluating how your activity, diet, and sleep influence clinical blood biomarkers.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {/* Insight 1: Activity & LDL */}
            <div className="p-6 rounded-3xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-sm flex flex-col justify-between space-y-4">
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <span className="text-[10px] font-bold uppercase tracking-wider text-cyan-600 flex items-center gap-1.5">
                    <Activity className="w-3.5 h-3.5" /> Physical Activity & Lipid Flux
                  </span>
                  <span className="text-[10px] px-2 py-0.5 rounded-full bg-emerald-100 dark:bg-emerald-950 text-emerald-700 dark:text-emerald-300 font-bold">
                    Improving
                  </span>
                </div>
                <h3 className="text-base font-bold text-slate-900 dark:text-white">
                  Walking Consistency Accelerated LDL Reduction
                </h3>
                <p className="text-xs text-slate-600 dark:text-slate-400 leading-relaxed">
                  <strong>What changed:</strong> You logged an average of 7,850 steps daily over the last 90 days (up 18%).
                </p>
                <p className="text-xs text-slate-600 dark:text-slate-400 leading-relaxed">
                  <strong>Why it matters:</strong> Regular moderate aerobic movement stimulates lecithin-cholesterol acyltransferase (LCAT) activity and assists hepatic low-density lipoprotein clearance.
                </p>
              </div>

              <div className="pt-3 border-t border-slate-100 dark:border-slate-800 flex items-center justify-between text-xs">
                <span className="text-slate-500 font-medium">Next step: Maintain 8,000 steps</span>
                <button
                  onClick={() => openAssistantWithPrompt("Explain the physiological mechanism of how daily walking helps clear LDL particles.")}
                  className="font-bold text-cyan-600 dark:text-cyan-400 hover:underline"
                >
                  Discuss with AI →
                </button>
              </div>
            </div>

            {/* Insight 2: Sleep & Resting Heart Rate */}
            <div className="p-6 rounded-3xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-sm flex flex-col justify-between space-y-4">
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <span className="text-[10px] font-bold uppercase tracking-wider text-indigo-600 flex items-center gap-1.5">
                    <Moon className="w-3.5 h-3.5" /> Sleep Architecture
                  </span>
                  <span className="text-[10px] px-2 py-0.5 rounded-full bg-cyan-100 dark:bg-cyan-950 text-cyan-700 dark:text-cyan-300 font-bold">
                    High Correlation
                  </span>
                </div>
                <h3 className="text-base font-bold text-slate-900 dark:text-white">
                  Nighttime Autonomic Dip & Vagal Recovery
                </h3>
                <p className="text-xs text-slate-600 dark:text-slate-400 leading-relaxed">
                  <strong>What changed:</strong> On nights when you slept before 11:00 PM (e.g. Sep 25), your nocturnal resting heart rate dropped to 60 bpm.
                </p>
                <p className="text-xs text-slate-600 dark:text-slate-400 leading-relaxed">
                  <strong>Why it matters:</strong> Consistent parasympathetic activation during deep slow-wave sleep prevents morning blood pressure surges.
                </p>
              </div>

              <div className="pt-3 border-t border-slate-100 dark:border-slate-800 flex items-center justify-between text-xs">
                <span className="text-slate-500 font-medium">Next step: 10:30 PM bedtime goal</span>
                <button
                  onClick={() => openAssistantWithPrompt("What sleep habits best support cardiovascular rest and lower my morning blood pressure?")}
                  className="font-bold text-cyan-600 dark:text-cyan-400 hover:underline"
                >
                  Discuss with AI →
                </button>
              </div>
            </div>

            {/* Insight 3: Hydration & Headache Journal */}
            <div className="p-6 rounded-3xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-sm flex flex-col justify-between space-y-4">
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <span className="text-[10px] font-bold uppercase tracking-wider text-blue-600 flex items-center gap-1.5">
                    <Droplets className="w-3.5 h-3.5" /> Symptom Correlation
                  </span>
                  <span className="text-[10px] px-2 py-0.5 rounded-full bg-amber-100 dark:bg-amber-950 text-amber-700 dark:text-amber-300 font-bold">
                    Actionable
                  </span>
                </div>
                <h3 className="text-base font-bold text-slate-900 dark:text-white">
                  Hydration Threshold Correlates with Tension Episodes
                </h3>
                <p className="text-xs text-slate-600 dark:text-slate-400 leading-relaxed">
                  <strong>What changed:</strong> All 3 recorded tension headaches coincided with days where water intake lagged below 1,600ml during prolonged screen sessions.
                </p>
                <p className="text-xs text-slate-600 dark:text-slate-400 leading-relaxed">
                  <strong>Why it matters:</strong> Mild cerebral dehydration enhances sensitivity to visual strain and vascular constriction.
                </p>
              </div>

              <div className="pt-3 border-t border-slate-100 dark:border-slate-800 flex items-center justify-between text-xs">
                <span className="text-slate-500 font-medium">Next step: Keep 750ml bottle at desk</span>
                <button
                  onClick={() => openAssistantWithPrompt("Summarize my tension headache entries and generate a note for my primary care doctor.")}
                  className="font-bold text-cyan-600 dark:text-cyan-400 hover:underline"
                >
                  Summarize for Doctor →
                </button>
              </div>
            </div>

            {/* Insight 4: Glycemic Stability */}
            <div className="p-6 rounded-3xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-sm flex flex-col justify-between space-y-4">
              <div className="space-y-2">
                <div className="flex items-center justify-between">
                  <span className="text-[10px] font-bold uppercase tracking-wider text-emerald-600 flex items-center gap-1.5">
                    <Heart className="w-3.5 h-3.5" /> Metabolic Health
                  </span>
                  <span className="text-[10px] px-2 py-0.5 rounded-full bg-emerald-100 dark:bg-emerald-950 text-emerald-700 dark:text-emerald-300 font-bold">
                    Normal Steady
                  </span>
                </div>
                <h3 className="text-base font-bold text-slate-900 dark:text-white">
                  HbA1c Improved to 5.6% Under High-Fiber Diet
                </h3>
                <p className="text-xs text-slate-600 dark:text-slate-400 leading-relaxed">
                  <strong>What changed:</strong> Your HbA1c declined from 5.7% (March) to 5.6% (September), safely under the prediabetes threshold.
                </p>
                <p className="text-xs text-slate-600 dark:text-slate-400 leading-relaxed">
                  <strong>Why it matters:</strong> Consistent dietary soluble fiber slows post-prandial glycemic excursions.
                </p>
              </div>

              <div className="pt-3 border-t border-slate-100 dark:border-slate-800 flex items-center justify-between text-xs">
                <span className="text-slate-500 font-medium">Status: Optimal Metabolic Reserve</span>
                <button
                  onClick={() => openAssistantWithPrompt("Explain the significance of an HbA1c change from 5.7% to 5.6%.")}
                  className="font-bold text-cyan-600 dark:text-cyan-400 hover:underline"
                >
                  Ask AI →
                </button>
              </div>
            </div>
          </div>
        </div>
      )}

      {/* TAB 2: DOCTOR VISIT PREPARATION & SUMMARY GENERATOR */}
      {activeTab === 'doctor-prep' && (
        <div className="space-y-6">
          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
            <div>
              <h2 className="text-xl font-bold text-slate-900 dark:text-white">
                Doctor Consultation Preparation Brief
              </h2>
              <p className="text-xs text-slate-500">
                Transform months of fragmented health data, lab results, and symptoms into a concise 1-page clinical summary.
              </p>
            </div>

            <button
              onClick={handleGenerateDoctorPrep}
              disabled={isGeneratingPrep}
              className="flex items-center gap-1.5 px-4 py-2.5 rounded-xl bg-gradient-to-r from-cyan-600 to-teal-600 hover:from-cyan-700 hover:to-teal-700 text-white text-xs font-bold shadow-md shadow-cyan-600/20 transition-all"
            >
              <Sparkles className="w-3.5 h-3.5" />
              <span>{isGeneratingPrep ? 'Synthesizing...' : 'Generate Consultation Brief'}</span>
            </button>
          </div>

          {/* Appointment Target Info Banner */}
          <div className="p-4 rounded-2xl bg-cyan-50 dark:bg-cyan-950/40 border border-cyan-200 dark:border-cyan-800/60 flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="p-2.5 rounded-xl bg-cyan-100 dark:bg-cyan-900 text-cyan-700 dark:text-cyan-200">
                <Calendar className="w-5 h-5" />
              </div>
              <div>
                <p className="text-xs font-bold text-slate-900 dark:text-white">
                  Target Encounter: {upcomingApt.doctor}
                </p>
                <p className="text-[11px] text-slate-500">
                  {upcomingApt.specialty} • {upcomingApt.date} at {upcomingApt.time}
                </p>
              </div>
            </div>
            <span className="text-[10px] font-semibold px-2 py-0.5 rounded-full bg-white dark:bg-slate-800 text-slate-600 dark:text-slate-300 border border-slate-200 dark:border-slate-700">
              Purpose: {upcomingApt.purpose}
            </span>
          </div>

          {/* Brief Content Output */}
          {prepSummary ? (
            <div className="p-6 rounded-3xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-md space-y-6 print:p-0 print:border-none">
              <div className="flex items-center justify-between border-b border-slate-100 dark:border-slate-800 pb-4">
                <div>
                  <h3 className="text-lg font-bold text-slate-900 dark:text-white">
                    {prepSummary.appointmentTitle}
                  </h3>
                  <p className="text-xs text-slate-400">
                    Patient: {patient.name} ({patient.age}y M) • Generated by AuraHealth AI
                  </p>
                </div>
                <div className="flex items-center gap-2">
                  <button
                    onClick={copyPrepToClipboard}
                    className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl border border-slate-200 dark:border-slate-700 text-xs font-semibold text-slate-700 dark:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors"
                  >
                    {copiedPrep ? <Check className="w-3.5 h-3.5 text-emerald-500" /> : <Copy className="w-3.5 h-3.5" />}
                    <span>{copiedPrep ? 'Copied' : 'Copy Brief'}</span>
                  </button>
                  <button
                    onClick={() => window.print()}
                    className="flex items-center gap-1.5 px-3 py-1.5 rounded-xl bg-slate-900 dark:bg-white text-white dark:text-slate-900 text-xs font-semibold hover:opacity-90 transition-opacity"
                  >
                    <Printer className="w-3.5 h-3.5" />
                    <span>Print Summary</span>
                  </button>
                </div>
              </div>

              {/* Executive Summary */}
              <div className="space-y-1">
                <h4 className="text-xs font-bold uppercase tracking-wider text-slate-400">
                  1. Executive Clinical Summary
                </h4>
                <p className="text-xs text-slate-700 dark:text-slate-300 leading-relaxed p-3.5 rounded-2xl bg-slate-50 dark:bg-slate-800/60">
                  {prepSummary.executiveSummary}
                </p>
              </div>

              {/* Key Metrics */}
              <div className="space-y-2">
                <h4 className="text-xs font-bold uppercase tracking-wider text-slate-400">
                  2. Priority Biomarkers & Vitals to Highlight
                </h4>
                <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
                  {prepSummary.keyMetricsToHighlight.map((m, idx) => (
                    <div key={idx} className="p-3 rounded-2xl border border-slate-200 dark:border-slate-700/60 bg-slate-50 dark:bg-slate-800/40 text-xs space-y-0.5">
                      <div className="flex items-center justify-between">
                        <span className="font-bold text-slate-900 dark:text-white">{m.metric}</span>
                        <span className="font-mono font-bold text-cyan-600">{m.value}</span>
                      </div>
                      <p className="text-[11px] text-slate-500">{m.note}</p>
                    </div>
                  ))}
                </div>
              </div>

              {/* Symptoms Summary */}
              <div className="space-y-1">
                <h4 className="text-xs font-bold uppercase tracking-wider text-slate-400">
                  3. Recorded Symptoms (Past 14 Days)
                </h4>
                <p className="text-xs text-slate-700 dark:text-slate-300 p-3 rounded-2xl bg-slate-50 dark:bg-slate-800/60">
                  {prepSummary.symptomsSummary}
                </p>
              </div>

              {/* Recommended Questions */}
              <div className="space-y-2">
                <h4 className="text-xs font-bold uppercase tracking-wider text-slate-400">
                  4. Recommended Questions for Your Doctor
                </h4>
                <div className="space-y-1.5">
                  {prepSummary.recommendedQuestionsForDoctor.map((q, idx) => (
                    <div key={idx} className="p-2.5 rounded-xl bg-cyan-50/60 dark:bg-cyan-950/30 border border-cyan-100 dark:border-cyan-900/40 text-xs text-slate-800 dark:text-slate-200 flex items-start gap-2">
                      <span className="w-4 h-4 rounded-full bg-cyan-600 text-white font-bold text-[10px] flex items-center justify-center shrink-0 mt-0.5">
                        {idx + 1}
                      </span>
                      <span>{q}</span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Preventive Checklist */}
              <div className="space-y-2">
                <h4 className="text-xs font-bold uppercase tracking-wider text-slate-400">
                  5. Routine Screening Discussion Points
                </h4>
                <div className="flex flex-wrap gap-2">
                  {prepSummary.preventiveChecklist.map((item, idx) => (
                    <span key={idx} className="text-xs px-3 py-1 rounded-xl bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300 border border-slate-200 dark:border-slate-700">
                      ✓ {item}
                    </span>
                  ))}
                </div>
              </div>
            </div>
          ) : (
            <div className="p-12 text-center bg-white dark:bg-slate-900 rounded-3xl border border-slate-200 dark:border-slate-800 space-y-3">
              <FileText className="w-12 h-12 text-slate-300 mx-auto" />
              <h3 className="text-base font-bold text-slate-800 dark:text-slate-200">
                No Consultation Brief Generated Yet
              </h3>
              <p className="text-xs text-slate-500 max-w-sm mx-auto">
                Click "Generate Consultation Brief" to compile your recent laboratory trends, medications, and symptoms into a clinical document.
              </p>
              <button
                onClick={handleGenerateDoctorPrep}
                className="px-4 py-2 rounded-xl bg-cyan-600 hover:bg-cyan-700 text-white text-xs font-bold transition-colors"
              >
                Generate Brief Now
              </button>
            </div>
          )}
        </div>
      )}

      {/* TAB 3: MONTHLY HEALTH REPORT */}
      {activeTab === 'report' && (
        <div className="space-y-6">
          <div className="flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
            <div>
              <h2 className="text-xl font-bold text-slate-900 dark:text-white">
                Comprehensive Periodic Health Report
              </h2>
              <p className="text-xs text-slate-500">
                Monthly or quarterly executive clinical summary of health pillars and trajectory
              </p>
            </div>

            <div className="flex items-center gap-2">
              <select
                value={selectedPeriod}
                onChange={(e) => setSelectedPeriod(e.target.value)}
                aria-label="Select Periodic Health Report Timeframe"
                className="text-xs font-bold rounded-xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-800 p-2 text-slate-800 dark:text-slate-200"
              >
                <option value="September 2026">September 2026 (Monthly)</option>
                <option value="Q3 2026">Q3 2026 (Quarterly)</option>
                <option value="Annual 2026">Annual 2026 Review</option>
              </select>

              <button
                onClick={handleGenerateReport}
                disabled={isGeneratingReport}
                className="flex items-center gap-1.5 px-3.5 py-2 rounded-xl bg-cyan-600 hover:bg-cyan-700 text-white text-xs font-bold shadow-xs transition-colors"
              >
                <Sparkles className="w-3.5 h-3.5" />
                <span>{isGeneratingReport ? 'Generating...' : 'Compile Report'}</span>
              </button>
            </div>
          </div>

          {generatedReport ? (
            <div className="p-8 rounded-3xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-md space-y-6">
              <div className="flex items-start justify-between border-b border-slate-100 dark:border-slate-800 pb-4">
                <div>
                  <span className="text-[10px] font-bold text-cyan-600 uppercase tracking-wider">
                    Executive Health Dossier
                  </span>
                  <h3 className="text-xl font-extrabold text-slate-900 dark:text-white mt-0.5">
                    {generatedReport.title}
                  </h3>
                  <p className="text-xs text-slate-400">
                    Patient: {patient.name} • Compiled on {generatedReport.generatedAt}
                  </p>
                </div>

                <div className="text-right">
                  <span className="text-3xl font-extrabold text-cyan-600">
                    {generatedReport.executiveScore}/100
                  </span>
                  <p className="text-[11px] font-semibold text-emerald-600">
                    {generatedReport.scoreStatus}
                  </p>
                </div>
              </div>

              {/* Pillars Grid */}
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                {generatedReport.keyPillars?.map((p: any, idx: number) => (
                  <div key={idx} className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200/80 dark:border-slate-700/60 space-y-1.5 text-xs">
                    <div className="flex items-center justify-between">
                      <span className="font-bold text-slate-900 dark:text-white">{p.pillar}</span>
                      <span className="font-mono font-bold text-cyan-600">{p.score}% ({p.status})</span>
                    </div>
                    <p className="text-slate-600 dark:text-slate-400 leading-relaxed">{p.note}</p>
                  </div>
                ))}
              </div>

              {/* Recommendations */}
              <div className="space-y-2 pt-2">
                <h4 className="text-xs font-bold uppercase tracking-wider text-slate-400">
                  Key Directives for the Coming Period
                </h4>
                <div className="space-y-1.5">
                  {generatedReport.recommendations?.map((rec: string, i: number) => (
                    <div key={i} className="flex items-start gap-2 text-xs text-slate-700 dark:text-slate-300">
                      <CheckCircle2 className="w-4 h-4 text-emerald-500 shrink-0 mt-0.5" />
                      <span>{rec}</span>
                    </div>
                  ))}
                </div>
              </div>

              <div className="pt-4 border-t border-slate-100 dark:border-slate-800 flex items-center justify-between text-xs text-slate-400">
                <span>{generatedReport.safetyNotice}</span>
                <button
                  onClick={() => window.print()}
                  className="px-3 py-1.5 rounded-xl bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 text-slate-700 dark:text-slate-200 font-semibold"
                >
                  Print Report
                </button>
              </div>
            </div>
          ) : (
            <div className="p-12 text-center bg-white dark:bg-slate-900 rounded-3xl border border-slate-200 dark:border-slate-800 space-y-3">
              <Printer className="w-12 h-12 text-slate-300 mx-auto" />
              <h3 className="text-base font-bold text-slate-800 dark:text-slate-200">
                Ready to Compile Monthly Report
              </h3>
              <p className="text-xs text-slate-500 max-w-sm mx-auto">
                Generate an end-of-month clinical review aggregating steps, sleep, cardiovascular metrics, and lab tests.
              </p>
              <button
                onClick={handleGenerateReport}
                className="px-4 py-2 rounded-xl bg-cyan-600 hover:bg-cyan-700 text-white text-xs font-bold transition-colors"
              >
                Compile September 2026 Report
              </button>
            </div>
          )}
        </div>
      )}

      {/* TAB 4: PREVENTIVE SCREENINGS */}
      {activeTab === 'preventive' && (
        <div className="space-y-6">
          <div>
            <h2 className="text-xl font-bold text-slate-900 dark:text-white">
              Evidence-Based Preventive Care Schedule
            </h2>
            <p className="text-xs text-slate-500">
              Personalized screening recommendations calibrated for a {patient.age}-year-old {patient.gender.toLowerCase()} based on USPSTF and AHA clinical guidelines.
            </p>
          </div>

          <div className="space-y-3">
            {PREVENTIVE_SCREENINGS.map((screening) => (
              <div
                key={screening.id}
                className="p-5 rounded-3xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-xs flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4"
              >
                <div className="space-y-1">
                  <div className="flex items-center gap-2">
                    <h3 className="text-sm font-bold text-slate-900 dark:text-white">
                      {screening.title}
                    </h3>
                    <span className="text-[10px] px-2 py-0.5 rounded-full bg-slate-100 dark:bg-slate-800 text-slate-500 font-mono">
                      {screening.guideline}
                    </span>
                  </div>
                  <p className="text-xs text-slate-500">
                    Frequency: {screening.frequency} • Target: {screening.targetAge}
                  </p>
                  <p className="text-xs text-slate-600 dark:text-slate-300">
                    {screening.relevance}
                  </p>
                </div>

                <div className="text-right shrink-0">
                  <span className={`inline-flex items-center px-2.5 py-1 rounded-xl text-xs font-bold ${
                    screening.statusBadge === 'completed'
                      ? 'bg-emerald-100 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-300'
                      : screening.statusBadge === 'active'
                      ? 'bg-cyan-100 text-cyan-800 dark:bg-cyan-950 dark:text-cyan-300'
                      : 'bg-amber-100 text-amber-800 dark:bg-amber-950 dark:text-amber-300'
                  }`}>
                    {screening.status}
                  </span>
                </div>
              </div>
            ))}
          </div>

          <div className="p-4 rounded-2xl bg-slate-100 dark:bg-slate-800/60 text-xs text-slate-500">
            *Clinical Note: Recommended screening intervals vary by regional public health bodies and your individual family history. Always verify with your primary physician.
          </div>
        </div>
      )}

      {/* TAB 5: UNIFIED TIMELINE */}
      {activeTab === 'timeline' && (
        <div className="space-y-6">
          <div>
            <h2 className="text-xl font-bold text-slate-900 dark:text-white">
              Unified Chronological Health Timeline
            </h2>
            <p className="text-xs text-slate-500">
              Interactive longitudinal record of laboratory tests, consultations, vaccinations, and medication start dates.
            </p>
          </div>

          <div className="relative pl-6 space-y-6 border-l-2 border-cyan-200 dark:border-cyan-800">
            {HISTORICAL_TIMELINE.map((event) => (
              <div key={event.id} className="relative group">
                {/* Dot Node */}
                <div className="absolute -left-[31px] top-1.5 w-4 h-4 rounded-full bg-cyan-500 ring-4 ring-white dark:ring-slate-900 group-hover:scale-125 transition-transform" />

                <div className="p-4 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-xs space-y-1">
                  <div className="flex items-center justify-between">
                    <span className="text-[10px] font-bold text-slate-400">
                      {event.date}
                    </span>
                    <span className="text-[10px] font-semibold px-2 py-0.5 rounded-full bg-cyan-50 dark:bg-cyan-950 text-cyan-700 dark:text-cyan-300">
                      {event.type}
                    </span>
                  </div>
                  <h4 className="text-sm font-bold text-slate-900 dark:text-white">
                    {event.title}
                  </h4>
                  <p className="text-xs text-slate-600 dark:text-slate-400">
                    {event.summary}
                  </p>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* TAB 6: GOALS & GAMIFICATION BADGES */}
      {activeTab === 'goals' && (
        <div className="space-y-6">
          <div>
            <h2 className="text-xl font-bold text-slate-900 dark:text-white">
              Health Goals & Engagement Milestones
            </h2>
            <p className="text-xs text-slate-500">
              Healthy habit streaks and achievements designed without unhealthy gamification pressure.
            </p>
          </div>

          {/* Goals List */}
          <div className="space-y-3">
            <h3 className="text-sm font-bold text-slate-900 dark:text-white">
              Active Targets
            </h3>
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {healthGoals.map((g) => (
                <div
                  key={g.id}
                  onClick={() => toggleGoalComplete(g.id)}
                  className="p-4 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-xs cursor-pointer hover:border-cyan-500 transition-all flex items-center justify-between"
                >
                  <div className="space-y-0.5">
                    <p className="text-xs font-bold text-slate-900 dark:text-white">
                      {g.title}
                    </p>
                    <p className="text-xs text-slate-500">
                      Target: {g.targetValue} {g.unit} (Current: {g.currentValue})
                    </p>
                    <span className="text-[10px] font-semibold text-amber-600 dark:text-amber-400 flex items-center gap-1">
                      <Flame className="w-3 h-3" /> {g.streakDays} day streak
                    </span>
                  </div>

                  <div className={`w-6 h-6 rounded-lg flex items-center justify-center border transition-colors ${
                    g.completed
                      ? 'bg-emerald-500 border-emerald-500 text-white'
                      : 'border-slate-300 dark:border-slate-700'
                  }`}>
                    {g.completed && <Check className="w-4 h-4" />}
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Badges Grid */}
          <div className="space-y-3 pt-4">
            <h3 className="text-sm font-bold text-slate-900 dark:text-white">
              Unlocked Achievements
            </h3>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
              {badges.map((b) => (
                <div key={b.id} className="p-4 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-xs flex items-center gap-3">
                  <div className="p-3 rounded-2xl bg-gradient-to-tr from-amber-400 to-orange-500 text-white shadow-xs">
                    <Award className="w-5 h-5" />
                  </div>
                  <div>
                    <h4 className="text-xs font-bold text-slate-900 dark:text-white">
                      {b.title}
                    </h4>
                    <p className="text-[11px] text-slate-500">{b.description}</p>
                    {b.unlockedAt && (
                      <span className="text-[10px] text-emerald-600 font-medium">✓ Unlocked</span>
                    )}
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* Safety Notice */}
      <SafetyBanner />
    </div>
  );
};
